version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samapp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xxjtym1198eb"
s3_prefix = "samapp"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
